### ISSUE TITLE
Showing TypeError: undefined is not iterable

### ISSUE THREAD

**Issue by vinayQA** [SharifClick/svelte-swipe#36]
[...swipeElements].forEach((element, i) => {
                ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at onEnd (C:\Users\Vinay\Samit\cbl\tool\__sapper__\dev\server\server.js:714:3)
    at changeItem (C:\Users\Vinay\Samit\cbl\tool\__sapper__\dev\server\server.js:727:3)
    at Timeout.changeView [as _onTimeout] (C:\Users\Vinay\Samit\cbl\tool\__sapper__\dev\server\server.js:731:3)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by dioxine** [comment]
same problem

**Comment by mylastore** [comment]
why an iframe been generated? Who uses iframes still?
